classdef FEMSetup < HandlePlus
    
    % rcs
    
	properties
        
        
        
        
        
        
        
        cName
  
    end
    
    properties (SetAccess = private)
    
    end
    
    properties (Access = private)
                      
        hPanel
        dWidth = 335
        dHeight = 400
        cl
        
    end
    
        
    events
        
        eName
        
    end
    

    
    methods
        
        
        function this = ProcessTool(cName, cl)
            
            this.cName = cName;
            this.cl = cl;
            this.init();
            
        end
        
                
        function build(this, hParent, dLeft, dTop)
                        
            
            this.hPanel = uipanel(...
                'Parent', hParent,...
                'Units', 'pixels',...
                'Title', 'Process Tool',...
                'Clipping', 'on',...
                'Position', Utils.lt2lb([dLeft dTop this.dWidth this.dHeight], hParent) ...
            );
			drawnow;
            
            dPadX = 10;
            dWidthName = 120;
            dWidthThick = 55;
            dWidthTemp = 55;
            dWidthTime = 55;
                     
            dTop = 20;
            dSep = 55;

            

            % Build filter Hz, Volts scale and time step

            
            this.uieUser.build( ...
                this.hPanel, ...
                dPadX, ...
                dTop, ...
                dWidthName, ...
                Utils.dEDITHEIGHT ...
            );
        
            dTop = dTop + dSep;
            
            this.uieUL1Name.build( ...
                this.hPanel, ...
                dPadX, ...
                dTop, ...
                dWidthName, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieUL1Thick.build( ...
                this.hPanel, ...
                2*dPadX + dWidthName, ...
                dTop, ...
                dWidthThick, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieUL1PABTemp.build( ...
                this.hPanel, ...
                3*dPadX + dWidthName + dWidthThick, ...
                dTop, ...
                dWidthTemp, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieUL1PABTime.build( ...
                this.hPanel, ...
                4*dPadX + dWidthName + dWidthThick + dWidthTemp, ...
                dTop, ...
                dWidthTime, ...
                Utils.dEDITHEIGHT ...
            );
        
        
        
            dTop = dTop + dSep;
            
            this.uieUL2Name.build( ...
                this.hPanel, ...
                dPadX, ...
                dTop, ...
                dWidthName, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieUL2Thick.build( ...
                this.hPanel, ...
                2*dPadX + dWidthName, ...
                dTop, ...
                dWidthThick, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieUL2PABTemp.build( ...
                this.hPanel, ...
                3*dPadX + dWidthName + dWidthThick, ...
                dTop, ...
                dWidthTemp, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieUL2PABTime.build( ...
                this.hPanel, ...
                4*dPadX + dWidthName + dWidthThick + dWidthTemp, ...
                dTop, ...
                dWidthTime, ...
                Utils.dEDITHEIGHT ...
            );
        
            dTop = dTop + dSep;
            
            this.uieResistName.build( ...
                this.hPanel, ...
                dPadX, ...
                dTop, ...
                dWidthName, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieResistThick.build( ...
                this.hPanel, ...
                2*dPadX + dWidthName, ...
                dTop, ...
                dWidthThick, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieResistPABTemp.build( ...
                this.hPanel, ...
                3*dPadX + dWidthName + dWidthThick, ...
                dTop, ...
                dWidthTemp, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieResistPABTime.build( ...
                this.hPanel, ...
                4*dPadX + dWidthName + dWidthThick + dWidthTemp, ...
                dTop, ...
                dWidthTime, ...
                Utils.dEDITHEIGHT ...
            );
        
            
        
        
            dTop = dTop + dSep;
            
            
            this.uieResistPEBTemp.build( ...
                this.hPanel, ...
                dPadX, ...
                dTop, ...
                dWidthTemp, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieResistPEBTime.build( ...
                this.hPanel, ...
                2*dPadX + dWidthTemp, ...
                dTop, ...
                dWidthTime, ...
                Utils.dEDITHEIGHT ...
            );
        
        
            dTop = dTop + dSep;
            
            this.uieDevName.build( ...
                this.hPanel, ...
                dPadX, ...
                dTop, ...
                dWidthName, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieDevTime.build( ...
                this.hPanel, ...
                2*dPadX + dWidthName, ...
                dTop, ...
                dWidthTime, ...
                Utils.dEDITHEIGHT ...
            );
        
            dTop = dTop + dSep;
            
            this.uieRinseName.build( ...
                this.hPanel, ...
                dPadX, ...
                dTop, ...
                dWidthName, ...
                Utils.dEDITHEIGHT ...
            );
        
            this.uieRinseTime.build( ...
                this.hPanel, ...
                2*dPadX + dWidthName, ...
                dTop, ...
                dWidthTime, ...
                Utils.dEDITHEIGHT ...
            );
        
        
            
        
            
        end
        
                        
        
        %% Destructor
        
        function delete(this)
            
            % Clean up clock tasks
            
            if (isvalid(this.cl))
                this.cl.remove(this.id());
            end
            
            
        end
        
        
        
        function handleClock(this)
            
            
            
            
        end
        
            

    end
    
    methods (Access = private)
        
        function init(this)
            
            this.uieUser            = UIEdit('User', 'c');
            this.uieBase            = UIEdit('Base', 'c');              
            this.uieUL1Name         = UIEdit('UL 1', 'c');
            this.uieUL1Thick        = UIEdit('Thick (nm)', 'u8');
            this.uieUL1PABTemp      = UIEdit('PAB Temp', 'u8');
            this.uieUL1PABTime      = UIEdit('PAB Time', 'u8');
            this.uieUL2Name         = UIEdit('UL 2', 'c');
            this.uieUL2Thick        = UIEdit('Thick (nm)', 'u8');
            this.uieUL2PABTemp      = UIEdit('PAB Temp', 'u8');
            this.uieUL2PABTime      = UIEdit('PAB Time', 'u8');
            this.uieResistName      = UIEdit('Resist', 'c');
            this.uieResistThick     = UIEdit('Thick (nm)', 'u8');
            this.uieResistPABTemp   = UIEdit('PAB Temp', 'u8');
            this.uieResistPABTime   = UIEdit('PAB Time', 'u8');
            this.uieResistPEBTemp   = UIEdit('PEB Temp', 'u8');
            this.uieResistPEBTime   = UIEdit('PEB Time', 'u8');
            this.uieDevName         = UIEdit('Dev', 'c');
            this.uieDevTime         = UIEdit('Dev Time', 'u8');
            this.uieRinseName       = UIEdit('Rinse Name', 'c');
            this.uieRinseTime       = UIEdit('Rinse Time', 'u8');
                    
            

        end
        
        
        function handleCloseRequestFcn(this, src, evt)
           
        end
        

    end % private
    
    
end