purge;

% Set current directory to the directory containing this file
[filepath, filename, ext] = fileparts(mfilename('fullpath'));
cd(filepath);

addpath(pwd);
addpath(fullfile(pwd,'classes'));


h = figure;
clock = Clock('Master');

m141 = StageXRxRy( ...
    fullfile(pwd, 'MotionControlProxy.jar'), ...
    'cxro.common.device.motion', ...
    'MotionControlProxy(''M141-Stage'',''iman.lbl.gov'')', ...
    'enableAxes()', ...
    'disableAxes()', ...
    'M141', ...
    clock);
m141.build(h, 10, 10);
